# Generated by Django 2.2.6 on 2019-10-05 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('codigo', models.IntegerField(max_length=10)),
                ('inscrito', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.CharField(max_length=100)),
                ('sede', models.CharField(max_length=15)),
                ('jornada', models.CharField(max_length=15)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Usuario')),
            ],
        ),
    ]
