# Generated by Django 2.2.6 on 2019-10-07 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0002_auto_20191004_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='estudiante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
